python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 5 -trial_index 23 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 5 -trial_index 24 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 5 -trial_index 25 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 5 -trial_index 26 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 7 -trial_index 23 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 7 -trial_index 24 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 7 -trial_index 25 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 7 -trial_index 26 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 9 -trial_index 18 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 9 -trial_index 19 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 9 -trial_index 20 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 9 -trial_index 21 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 9 -trial_index 22 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 9 -trial_index 23 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 9 -trial_index 24 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 9 -trial_index 25 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 9 -trial_index 26 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 9 -trial_index 27 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 9 -trial_index 28 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 9 -trial_index 29 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 9 -trial_index 30 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 11 -trial_index 23 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 11 -trial_index 24 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 11 -trial_index 25 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 11 -trial_index 26 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 13 -trial_index 20 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 13 -trial_index 23 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 13 -trial_index 24 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 13 -trial_index 25 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MED -state_distribution uncertain -num_learners 13 -trial_index 26 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 9 -trial_index 18 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 9 -trial_index 19 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 9 -trial_index 20 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 9 -trial_index 21 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 9 -trial_index 22 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 9 -trial_index 23 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 9 -trial_index 24 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 9 -trial_index 25 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 9 -trial_index 26 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 9 -trial_index 27 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 9 -trial_index 28 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 9 -trial_index 29 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 9 -trial_index 30 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 11 -trial_index 22 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 13 -trial_index 17 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution uncertain -num_learners 13 -trial_index 27 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 9 -trial_index 18 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 9 -trial_index 19 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 9 -trial_index 20 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 9 -trial_index 21 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 9 -trial_index 22 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 9 -trial_index 23 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 9 -trial_index 24 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 9 -trial_index 25 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 9 -trial_index 26 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 9 -trial_index 27 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 9 -trial_index 28 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 9 -trial_index 29 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 9 -trial_index 30 -experiment_name num_learners
python orchestrator.py -data_allocation_regime MMTT -state_distribution ideal -num_learners 13 -trial_index 29 -experiment_name num_learners


echo all done!
echo going to sleep now bye
systemctl suspend